---
title: "DHARMa Demo"
author: "Florian Hartig"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A demo of the package}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8](inputenc)
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, warning=FALSE, message=FALSE)
```


```{r}
library(DHARMa)
library(lme4)
```



## Example analysis for Poisson model

```{r}
testData = createPoissonData(sampleSize = 2000)[[1]]
# see ?createPoissonData for paramter values
```

Standard analysis + standard residuals

```{r}
fittedModel <- glmer(counts ~ environment1 + (1|group) + (1|ID) , family = "poisson", data = testData)
summary(fittedModel)
par(mfrow = c(1,3))
plot(predict(fittedModel), resid(fittedModel, type = "deviance"), main = "Deviance" )
plot(predict(fittedModel), resid(fittedModel, type = "pearson") , main = "Pearson")
plot(predict(fittedModel), resid(fittedModel, type = "response") , main = "Pearson" )

```

Simulated Residuals

```{r}
simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput)
```


# Binomial model

```{r}
testData = createBinomialData(sampleSize = 2000)[[1]]
# see ?createPoissonData for paramter values
```

Standard analysis + standard residuals

```{r}
fittedModel <- glmer(counts ~ environment1 + (1|group) , family = "binomial", data = testData)
summary(fittedModel)
par(mfrow = c(1,3))
plot(predict(fittedModel), resid(fittedModel, type = "deviance"), main = "Deviance" )
plot(predict(fittedModel), resid(fittedModel, type = "pearson") , main = "Pearson")
plot(predict(fittedModel), resid(fittedModel, type = "response") , main = "Pearson" )

```

Simulated Residuals

```{r}
simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput)
```







