---
title: "Calibration of p-values"
author: "Florian Hartig"
date: "6/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)
```


```{r}
library(DHARMa)
```



```{r}
  reps = 200

  pValsOutliers = matrix(ncol = 6, nrow = reps)
  pValsDispersion = matrix(ncol = 3, nrow = reps)
  pValsKS = rep(NA, reps)

  

  for(i in 1:reps){
    testData = createData(sampleSize = 1000, overdispersion = 0, pZeroInflation = 0, randomEffectVariance = 0, family = gaussian())
    fittedModel <- lm(observedResponse ~ Environment1 , data = testData)
    simulationOutput <- simulateResiduals(fittedModel = fittedModel, n = 100)
    
    
    pValsOutliers[i,1] = testOutliers(simulationOutput, plot = F, alternative = "two.sided")$p.value
    pValsOutliers[i,2] = testOutliers(simulationOutput, plot = F, alternative = "greater")$p.value
    pValsOutliers[i,3] = testOutliers(simulationOutput, plot = F, alternative = "less")$p.value

    pValsOutliers[i,4] = testOutliers(simulationOutput, plot = F, alternative = "two.sided", margin = "upper")$p.value
    pValsOutliers[i,5] = testOutliers(simulationOutput, plot = F, alternative = "greater", margin = "upper")$p.value
    pValsOutliers[i,6] = testOutliers(simulationOutput, plot = F, alternative = "less", margin = "upper")$p.value
    
    pValsDispersion[i,1] = testDispersion(simulationOutput, plot = F, alternative = "two.sided")$p.value
    pValsDispersion[i,2] = testDispersion(simulationOutput, plot = F, alternative = "greater")$p.value
    pValsDispersion[i,3] = testDispersion(simulationOutput, plot = F, alternative = "less")$p.value
    
    pValsKS[i] = testUniformity(simulationOutput, plot = F)$p.value
  }
  
```



```{r}
par(mfrow = c(2,3))
for(i in 1:6) hist(pValsOutliers[,i], breaks = 50)
```



