---
title: "PowerTests"
author: "Florian Hartig"
date: "5/12/2018"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4.5, fig.align='center', warning=FALSE, message=FALSE, cache = T)
```

```{r, echo = F}
library(AER)
library(lme4)
library(glmmTMB)
library(DHARMa)
```

# Dispersion Tests

Importance of overdispersion 

```{r}
returnStatistics <- function(control = 1){
  testData = createData(sampleSize = 200, family = poisson(), overdispersion = control, fixedEffects = 0,
                        randomEffectVariance = 0)
  fittedModel <- glm(observedResponse ~ Environment1, data = testData, family = poisson())
  x = summary(fittedModel)
  res <- simulateResiduals(fittedModel = fittedModel, n = 250)
  out <- c("Type I error GLM slope" = x$coefficients[2,4], "DHARMa testDispersion" = testDispersion(res, plot = FALSE)$p.value)
  return(out)
}

# running benchmark for a fixed simulation, increase nRep for sensible results
# out = runBenchmarks(returnStatistics, nRep = 100)
# plot(out)

out = runBenchmarks(returnStatistics, controlValues = seq(0, 1.5, 0.1), nRep = 100)
plot(out, xlab = "Overdispersion", xlab = "True overdispersion")
```




## Benchmarking DHARMa dispersiontests against AER dispersiontest for Poisson GLM

```{r}
doCalculations <- function(control = 0){
  
  testData = createData(sampleSize = 200, family = poisson(), overdispersion = control, randomEffectVariance = 0)
  fittedModel <- glm(observedResponse ~ Environment1, data = testData, family = poisson())
 
  out = list()

  res <- simulateResiduals(fittedModel = fittedModel, n = 250)
  out$uniformTest = testUniformity(res, plot = F)$p.value  
  out$Dispersion = testDispersion(res, plot = F)$p.value  
  out$DispersionAER = AER::dispersiontest(fittedModel)$p.value
  out$DispPerformance = performance::check_overdispersion(fittedModel)$p_value
  
  res <- simulateResiduals(fittedModel = fittedModel, n = 250, refit = F)  
  out$DispersionRefitted = testDispersion(res, plot = F)$p.value  
  return(unlist(out))
}

# testing a single return
doCalculations(control = 0.3)

dispValues = seq(0,1.2, len = 20)

# running benchmark
out = runBenchmarks(doCalculations, controlValues = dispValues , nRep = 1000,  parallel = F)

tests = c("uniformity", "DHARMa disp basic" , "AER dispersiontest","performanceDisp", "DHARMa disp refit")


matplot(dispValues, t(out$summaries[,1,]), type = "l")
legend("bottomright", tests, col = 1:5, lty = 1:5)

```



## Benchmarking DHARMa dispersiontests against AER dispersiontest for Poisson GLM

```{r}

overdisp_fun <- function(model) {
  ## number of variance parameters in 
  ##   an n-by-n variance-covariance matrix
  vpars <- function(m) {
    nrow(m)*(nrow(m)+1)/2
  }
  model.df <- sum(sapply(VarCorr(model),vpars))+length(fixef(model))
  rdf <- nrow(model.frame(model))-model.df
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(Pearson.chisq, df=rdf, lower.tail=FALSE)
  list(chisq=Pearson.chisq,ratio=prat,rdf=rdf,p=pval)
}

doCalculations <- function(control = 0){
  testData = createData(sampleSize = 200, family = poisson(), overdispersion = control, randomEffectVariance = 1)
  fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), data = testData, family = poisson())
 
  out = list()
  
  res <- simulateResiduals(fittedModel = fittedModel, n = 250)
  out$uniformTest = testUniformity(res)$p.value  
  out$Dispersion = testDispersion(res, plot = F)$p.value  
  out$DispersionAER = overdisp_fun(fittedModel)$p.value
  
  res <- simulateResiduals(fittedModel = fittedModel, n = 250, refit = T)  
  out$DispersionRefitted = testDispersion(res, plot = F)$p.value  
  return(unlist(out))
}

# testing a single return
doCalculations(control = 0.3)

dispValues = seq(0,1.2, len = 5)

# running benchmark
out = runBenchmarks(doCalculations, controlValues = dispValues , nRep = 10,  parallel = T)

tests = c("uniformity", "DHARMa disp basic" , "GLMER dispersiontest", "DHARMa disp refit")


matplot(dispValues, t(out$summaries[,1,]), type = "l")
legend("bottomright", tests, col = 1:4, lty = 1:4)

```



# Autocorrelation tests





